version: '3.8'

services:
  postgres:
    image: 'casedasa.azurecr.io/postgres:latest'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB= dasa
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  case-dasa:
    image: 'casedasa.azurecr.io/casedasa:latest'
    build:
      context: /home/guidini/Desktop/case/
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

volumes:
  postgres-data:
    driver: azure_file
    driver_opts:
        share_name: postgresql
        storage_account_name: psqlcaseapi